/*
 * Copyright (c) 2023 teemEight
 * SPDX-License-Identifier: Apache-2.0
 */

package repository.neo4jEntities

import org.neo4j.ogm.annotation.*
import repository.serialization.Metadata
import repository.serialization.SerializableValue

@NodeEntity("Node")
class Neo4jNodeEntity(

    //serializable node value stored in the database as a string.
    @Property("data")
    var data: SerializableValue,
    //node metadata stored in the database as a string.
    @Property("metadata")
    var metadata: Metadata,
    //reference to the left child node in the tree structure.
    @Relationship(type = "LEFT", direction = Relationship.Direction.OUTGOING)
    var left: Neo4jNodeEntity? = null,
    //reference to the right child node in the tree structure.
    @Relationship(type = "RIGHT", direction = Relationship.Direction.OUTGOING)
    var right: Neo4jNodeEntity? = null,
) {
    //the node ID generated by the database on save.
    @Id
    @GeneratedValue
    var id: Long? = null
}