name: Build CI

on:
  pull_request:
    branches:
      - main
      - release

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu
      - name: Build & test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build